import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from 'react';

const translations = {
  UA: {
    'checkout.name': "Ім'я",
    'checkout.phone': 'Телефон',
    'checkout.address': 'Адреса',
    'checkout.items': 'Товари',
    'checkout.delivery': 'Доставка',
    'checkout.free': 'Безкоштовно',
    'checkout.total': 'Всього',
    'checkout.submit': 'Замовити',
    'checkout.placeholder.name': "Ваше ім'я",
    'checkout.placeholder.phone': '+38 (0XX) XXX-XX-XX',
    'checkout.placeholder.address': 'Місто, вулиця, дім',
    'checkout.placeholder.city': 'Місто',
    'checkout.placeholder.warehouse': 'Номер відділення Нової Пошти',
    'checkout.np_warehouse': 'Нова Пошта, відділення',
    'checkout.city': 'Місто',
    'checkout.prepay': 'Передплата на картку',
    'checkout.prepay.hint': 'Оплачуйте замовлення відразу на картку для економії на післяплаті Нової Пошти',
    'cart.title': 'Кошик',
    'cart.view': 'Переглянути кошик',
    'cart.empty': 'Кошик порожній',
    'cart.continue': 'Продовжити покупки',
    'cart.summary': 'Замовлення',
    'cart.subtotal': 'Сума',
    'cart.shipping': 'Доставка',
    'cart.shipping.calc': 'Розраховується',
    'cart.total': 'Всього',
    'cart.checkout': 'Оформити замовлення',
    'order.title': 'Замовлення підтверджено',
    'order.message': 'Дякуємо! Ми зв\'яжемося з вами найближчим часом.',
    'order.number': 'Номер',
    'order.amount': 'Сума',
    'order.included': 'Включено',
    'order.free': 'Безкоштовно',
    'order.charged': 'Списано з карти',
    'order.continue': 'Продовжити',
    'product.notfound': 'Товар не знайдено',
    'product.back': 'Назад',
    'product.size': 'Розмір',
    'product.add': 'В кошик',
    'product.added': '✓ В кошику',
    'product.negotiate': 'Запропонувати ціну',
    'product.negotiate.title': 'Запропонуйте свою ціну',
    'product.negotiate.subtitle': 'Напишіть суму, яку ви готові заплатити, і ми обговоримо',
    'product.negotiate.placeholder': 'Ваша ціна',
    'product.negotiate.send': 'Надіслати пропозицію',
    'product.negotiate.msg': 'Вітаю, хочу запропонувати',
    'product.negotiate.for': 'за товар',
    'profile.title': 'Профіль',
    'profile.admin': 'Адмін',
    'profile.panel': 'Панель керування',
    'profile.support': 'Підтримка',
    'profile.write': 'Написати нам',
    'store.tag': 'Магазин',
    'nav.store': 'Магазин',
    'nav.cart': 'Кошик',
    'nav.favorites': 'Обрані',
    'nav.settings': 'Налаштування',
    'store.hero.tag': 'Нова колекція',
    'store.hero.button': 'ДИВИТИСЯ',
    'store.categories.title': 'Категорії',
    'store.categories.all': 'Всі',
    'store.products.title': 'Товари',
    'store.products.all': 'Всі',
    'products.title': 'Товари',
    'products.count': 'товарів',
    'products.sort.default': 'За замовчуванням',
    'products.sort.price.asc': 'Ціна: від низької',
    'products.sort.price.desc': 'Ціна: від високої',
    'products.sort.name.asc': 'Назва: А-Я',
    'products.sort.name.desc': 'Назва: Я-А',
    'admin.title': 'Панель керування',
    'admin.products': 'Товари',
    'admin.orders': 'Замовлення',
    'admin.shipping': 'Доставка',
    'admin.order.delete': 'Видалити',
    'admin.add.product': 'Додати товар',
    'admin.product.name': 'Назва товару',
    'admin.product.category': 'Категорія',
    'admin.product.price': 'Ціна',
    'admin.product.photo': 'Фото товару',
    'admin.product.photo.placeholder': 'Виберіть файл або введіть URL',
    'admin.product.description': 'Опис',
    'admin.product.add': 'Додати товар',
    'admin.photos.title': 'Фото',
    'admin.photos.hint': 'Натисніть, щоб змінити фото товару',
    'admin.photos.available': 'Доступні фото',
    'admin.photos.tap': 'Натисніть, щоб змінити',
    'admin.dashboard': 'Огляд',
    'admin.access.denied': 'Доступ заборонено',
    'cart.size': 'Розмір',
    'lang.ua': 'Українська',
    'lang.ru': 'Русский',
    'settings.lang': 'Мова',
    'categories.All': 'Всі',
    'categories.Outerwear': 'Верхній одяг',
    'categories.Accessories': 'Аксесуари',
    'categories.Tops': 'Верх',
    'categories.Bottoms': 'Низ',
    'categories.Shoes': 'Взуття',
    'categories.General': 'Загальне',
    'cart.item.one': 'товар',
    'cart.item.few': 'товари',
    'cart.item.many': 'товарів',
    'admin.collection': 'Колекція',
    'admin.users': 'Користувачі',
    'admin.data': 'Дані',
    'admin.cancel': 'Скасувати',
    'admin.deal.add': 'Додати персональну знижку',
    'admin.deal.remove': 'Видалити знижку',
    'admin.deal.active': 'Персональна знижка',
    'admin.deal.note': 'Нотатка',
    'admin.data.clear': 'Очистити',
    'admin.data.clear_all': 'Очистити всі дані',
    'admin.data.danger': 'Небезпечна зона',
    'admin.data.danger.desc': 'Це видалить всі товари, замовлення та скине налаштування. Дія незворотна.',
    'admin.data.confirm': 'Так, видалити все',
    'admin.no.users': 'Ще немає користувачів',
    'admin.np.title': 'Nova Poshta налаштування',
    'admin.np.hint': 'Отримайте ці дані в особистому кабінеті Nova Poshta (API → Налаштування відправника). Обов\'язкові для автоматичного створення ТТН.',
    'admin.np.sender_ref': 'Sender Ref (Counterparty)',
    'admin.np.sender_address_ref': 'Sender Address Ref',
    'admin.np.contact_sender_ref': 'Contact Sender Ref',
    'admin.np.city_sender_ref': 'City Sender Ref',
    'admin.np.sender_phone': 'Sender Phone',
    'admin.np.city': 'Місто відправника',
    'admin.np.warehouse': 'Відділення відправника',
    'admin.np.configured': 'Налаштовано',
    'admin.np.test': 'Тест API',
    'admin.np.save': 'Зберегти',
    'admin.np.saving': 'Збереження...',
    'admin.np.saved': 'Збережено!',
    'admin.collection.title': 'Назва колекції',
    'admin.collection.subtitle': 'Підзаголовок',
    'admin.collection.tag': 'Тег',
    'admin.collection.save': 'Зберегти',
    'admin.collection.show': 'Показувати колекцію на головній',

    'shipping.np_price': 'Вартість доставки НП (₴)',
    'shipping.free_threshold': 'Безкоштовно від суми (₴)',
    'admin.product.sizes': 'Розміри (через кому, напр. S, M, L, XL)',
    'admin.product.collections': 'Колекції (через кому, напр. Summer, Winter)',
    'admin.product.save': 'Зберегти товар',
    'admin.product.in_collection': 'Показувати в колекції',
    'admin.product.stock': 'Кількість',
    'product.out_of_stock': 'Немає в наявності',
    'product.out_of_stock_short': 'Немає',
    'product.stock': 'В наявності',
    'product.condition.new': 'Новий',
    'product.condition.like_new': 'Як новий',
    'product.condition.good': 'Хороший',
    'product.condition.fair': 'Задовільний',
    'cart.promo': 'Промокод',
    'cart.apply': 'Застосувати',
    'cart.tax': 'Податок',
    'cart.discount': 'Знижка',
    'cart.shipping.free': 'Безкоштовно',
    'cart.bag': 'Кошик',
    'cart.item.label': 'товар',
    'cart.items.label': 'товар(-и)',
    'store.hero.text': 'Ефірне тепло, створене для холоду.',
    'store.view.collection': 'ДИВИТИСЬ КОЛЕКЦІЮ',
    'store.new.arrivals': 'Новинки',
    'store.view.all': 'Всі',
    'store.categories': 'Категорії',
    'store.featured': 'Рекомендуємо',
    'settings.darkmode': 'Темна тема',
    'settings.preferences': 'Налаштування',
    'settings.version': 'Версія',
    'settings.history': 'Історія замовлень',
    'settings.orders': 'замовлень',
    'settings.no.orders': 'Ще немає замовлень',
    'favorites.empty': 'Немає обраних',
    'favorites.title': 'Обрані',
    'favorites.browse': 'Переглянути товари',
    'cart.empty.text': 'Ваш кошик порожній',
    'product.quantity': 'Кількість',
    'product.description': 'Опис',
    'product.materials': 'Матеріали',
    'product.care': 'Догляд',
    'product.see.all': 'Всі',
    'order.reference': 'Номер замовлення',
    'order.status': 'Статус',
    'order.shipping': 'Доставка',
    'order.payment': 'Оплата',
    'order.arrival': 'Очікувана дата',
    'settings.panel': 'Панель керування',
    'checkout.title': 'Оформлення',
    'checkout.contact': 'Контактна інформація',
    'checkout.summary': 'Підсумок',
    'checkout.place': 'Замовити',
    'checkout.processing': 'Обробка...',
    'favorites.save': 'Зберігайте улюблені речі',
    'favorites.discover': 'Переглянути товари',
    'order.confirmed': 'ЗАМОВЛЕННЯ ПІДТВЕРДЖЕНО',
    'order.confirmed.msg': 'Ваші товари готуються з турботою.',
    'order.tracking': 'Статус',
    'order.step.confirmed': 'Підтверджено',
    'order.step.processing': 'Обробляється',
    'order.step.shipped': 'Відправлено',
    'order.step.delivered': 'Доставлено',
    'order.ship.address': 'Адреса доставки',
    'order.pay.method': 'Спосіб оплати',
    'product.rating': 'Рейтинг',
    'product.size.guide': 'Гід по розмірам',
    'product.ecosystem': 'ДОКОМПЛЕКТ',
    'product.complete': 'Доповніть образ',
    'store.hero.title': 'ЗИМОВА КОЛЕКЦІЯ',
    'store.highlight.tag': 'СЕРІЯ',
    'store.cat.all': 'Всі',
    'store.cat.outerwear': 'Верхній одяг',
    'store.cat.accessories': 'Аксесуари',
    'store.cat.tops': 'Верх',
    'store.cat.bottoms': 'Низ',
    'store.cat.shoes': 'Взуття',
    'product.size.text': 'Розмір',
    'order.shipping.text': 'Доставка',
    'order.total.text': 'Всього',
    'order.complimentary': 'Безкоштовно',
    'order.continue.shopping': 'ПРОДОВЖИТИ',
    'order.message.seller': 'НАПИСАТИ ПРОДАВЦЮ',
    'settings.version.suffix': '-ГЛЯЦІЙ',
    'admin.product.subcategory': 'Підкатегорія',
    'admin.product.photos': 'Фото',
    'admin.form.basic_info': 'Основна інформація',
    'admin.form.pricing': 'Ціна та кількість',
    'admin.form.details': 'Деталі',
    'admin.form.upload': 'Завантажити',
    'admin.form.url': 'Посилання',
    'admin.form.first_is_primary': 'перше фото — головне',
    'admin.form.add_photo': 'Додати ще фото',
    'admin.no.products': 'Товарів ще немає',
    'products.empty.category': 'У цій категорії ще немає товарів',
    'products.empty.hint': 'Спробуйте іншу категорію або завітайте пізніше',
    'admin.product.sizes_label': 'Розміри (натисніть, щоб обрати)',
    'admin.product.collections_label': 'Колекції',
    'admin.form.custom_size': 'Свій розмір',
    'admin.form.custom_collection': 'Нова колекція',
    'admin.form.add': 'Додати',
  },
  RU: {
    'checkout.name': 'Имя',
    'checkout.phone': 'Телефон',
    'checkout.address': 'Адрес',
    'checkout.items': 'Товары',
    'checkout.delivery': 'Доставка',
    'checkout.free': 'Бесплатно',
    'checkout.total': 'Итого',
    'checkout.submit': 'Заказать',
    'checkout.placeholder.name': 'Ваше имя',
    'checkout.placeholder.phone': '+38 (0XX) XXX-XX-XX',
    'checkout.placeholder.address': 'Город, улица, дом',
    'checkout.placeholder.city': 'Выберите город',
    'checkout.placeholder.warehouse': 'Выберите отделение',
    'checkout.np_warehouse': 'Отделение',
    'checkout.city': 'Город',
    'checkout.prepay': 'Предоплата',
    'checkout.prepay.hint': 'Оплата картой сейчас. Товары отправляются после оплаты.',
    'cart.title': 'Корзина',
    'cart.view': 'Посмотреть корзину',
    'cart.empty': 'Корзина пуста',
    'cart.continue': 'Продолжить покупки',
    'cart.summary': 'Заказ',
    'cart.subtotal': 'Сумма',
    'cart.shipping': 'Доставка',
    'cart.shipping.calc': 'Рассчитывается',
    'cart.total': 'Итого',
    'cart.checkout': 'Оформить заказ',
    'order.title': 'Заказ подтвержден',
    'order.message': 'Спасибо! Мы свяжемся с вами в ближайшее время.',
    'order.number': 'Номер',
    'order.amount': 'Сумма',
    'order.included': 'Включено',
    'order.free': 'Бесплатно',
    'order.charged': 'Списано с карты',
    'order.continue': 'Продолжить',
    'product.notfound': 'Товар не найден',
    'product.back': 'Назад',
    'product.size': 'Размер',
    'product.add': 'В корзину',
    'product.added': '✓ В корзине',
    'product.negotiate': 'Предложить цену',
    'product.negotiate.title': 'Предложите свою цену',
    'product.negotiate.subtitle': 'Напишите сумму, которую вы готовы заплатить, и мы обсудим',
    'product.negotiate.placeholder': 'Ваша цена',
    'product.negotiate.send': 'Отправить предложение',
    'product.negotiate.msg': 'Здравствуйте, хочу предложить',
    'product.negotiate.for': 'за товар',
    'profile.title': 'Профиль',
    'profile.admin': 'Админ',
    'profile.panel': 'Панель управления',
    'profile.support': 'Поддержка',
    'profile.write': 'Написать нам',
    'store.tag': 'Магазин',
    'nav.store': 'Магазин',
    'nav.cart': 'Корзина',
    'nav.favorites': 'Избранное',
    'nav.settings': 'Настройки',
    'store.hero.tag': 'Новая коллекция',
    'store.hero.button': 'СМОТРЕТЬ',
    'store.categories.title': 'Категории',
    'store.categories.all': 'Все',
    'store.products.title': 'Товары',
    'store.products.all': 'Все',
    'products.title': 'Товары',
    'products.count': 'товаров',
    'products.sort.default': 'По умолчанию',
    'products.sort.price.asc': 'Цена: по возрастанию',
    'products.sort.price.desc': 'Цена: по убыванию',
    'products.sort.name.asc': 'Название: А-Я',
    'products.sort.name.desc': 'Название: Я-А',
    'admin.title': 'Панель управления',
    'admin.products': 'Товары',
    'admin.orders': 'Заказы',
    'admin.shipping': 'Доставка',
    'admin.order.delete': 'Удалить',
    'admin.add.product': 'Добавить товар',
    'admin.product.name': 'Название товара',
    'admin.product.category': 'Категория',
    'admin.product.price': 'Цена',
    'admin.product.photo': 'Фото товара',
    'admin.product.photo.placeholder': 'Выберите файл или введите URL',
    'admin.product.description': 'Описание',
    'admin.product.add': 'Добавить товар',
    'admin.photos.title': 'Фото',
    'admin.photos.hint': 'Нажмите, чтобы сменить фото товара',
    'admin.photos.available': 'Доступные фото',
    'admin.photos.tap': 'Нажмите, чтобы сменить',
    'admin.dashboard': 'Обзор',
    'admin.access.denied': 'Доступ запрещен',
    'cart.size': 'Размер',
    'lang.ua': 'Українська',
    'lang.ru': 'Русский',
    'settings.lang': 'Язык',
    'categories.All': 'Все',
    'categories.Outerwear': 'Верхняя одежда',
    'categories.Accessories': 'Аксессуары',
    'categories.Tops': 'Верх',
    'categories.Bottoms': 'Низ',
    'categories.Shoes': 'Обувь',
    'categories.General': 'Общее',
    'cart.item.one': 'товар',
    'cart.item.few': 'товара',
    'cart.item.many': 'товаров',
    'admin.collection': 'Коллекция',
    'admin.users': 'Пользователи',
    'admin.data': 'Данные',
    'admin.cancel': 'Отмена',
    'admin.deal.add': 'Добавить персональную скидку',
    'admin.deal.remove': 'Удалить скидку',
    'admin.deal.active': 'Персональная скидка',
    'admin.deal.note': 'Заметка',
    'admin.data.clear': 'Очистить',
    'admin.data.clear_all': 'Очистить все данные',
    'admin.data.danger': 'Опасная зона',
    'admin.data.danger.desc': 'Это удалит все товары, заказы и сбросит настройки. Действие необратимо.',
    'admin.data.confirm': 'Да, удалить все',
    'admin.no.users': 'Еще нет пользователей',
    'admin.np.title': 'Настройки Nova Poshta',
    'admin.np.hint': 'Получите эти данные в личном кабинете Nova Poshta (API → Настройки отправителя). Обязательны для автоматического создания ТТН.',
    'admin.np.sender_ref': 'Sender Ref (Контрагент)',
    'admin.np.sender_address_ref': 'Sender Address Ref',
    'admin.np.contact_sender_ref': 'Contact Sender Ref',
    'admin.np.city_sender_ref': 'City Sender Ref',
    'admin.np.sender_phone': 'Телефон отправителя',
    'admin.np.city': 'Город отправителя',
    'admin.np.warehouse': 'Отделение отправителя',
    'admin.np.configured': 'Настроено',
    'admin.np.test': 'Тест API',
    'admin.np.save': 'Сохранить',
    'admin.np.saving': 'Сохранение...',
    'admin.np.saved': 'Сохранено!',
    'admin.collection.title': 'Название коллекции',
    'admin.collection.subtitle': 'Подзаголовок',
    'admin.collection.tag': 'Тег',
    'admin.collection.save': 'Сохранить',
    'admin.collection.show': 'Показывать коллекцию на главной',

    'shipping.np_price': 'Стоимость доставки НП (₴)',
    'shipping.free_threshold': 'Бесплатно от суммы (₴)',
    'admin.product.sizes': 'Размеры (через запятую, напр. S, M, L, XL)',
    'admin.product.collections': 'Коллекции (через запятую, напр. Summer, Winter)',
    'admin.product.save': 'Сохранить товар',
    'admin.product.in_collection': 'Показывать в коллекции',
    'admin.product.stock': 'Количество',
    'product.out_of_stock': 'Нет в наличии',
    'product.out_of_stock_short': 'Нет',
    'product.stock': 'В наличии',
    'product.condition.new': 'Новый',
    'product.condition.like_new': 'Как новый',
    'product.condition.good': 'Хорошее',
    'product.condition.fair': 'Удовлетворительное',
    'cart.promo': 'Промокод',
    'cart.apply': 'Применить',
    'cart.tax': 'Налог',
    'cart.discount': 'Скидка',
    'cart.shipping.free': 'Бесплатно',
    'cart.bag': 'Корзина',
    'cart.item.label': 'товар',
    'cart.items.label': 'товар(ы)',
    'store.hero.text': 'Невесомое тепло для тех, кто не мерзнет.',
    'store.view.collection': 'СМОТРЕТЬ КОЛЛЕКЦИЮ',
    'store.new.arrivals': 'Новинки',
    'store.view.all': 'Все',
    'store.categories': 'Категории',
    'store.featured': 'Рекомендуем',
    'settings.darkmode': 'Темная тема',
    'settings.preferences': 'Настройки',
    'settings.version': 'Версия',
    'settings.history': 'История заказов',
    'settings.orders': 'заказов',
    'settings.no.orders': 'Еще нет заказов',
    'favorites.empty': 'Нет избранных',
    'favorites.title': 'Избранное',
    'favorites.browse': 'Посмотреть товары',
    'cart.empty.text': 'Ваша корзина пуста',
    'product.quantity': 'Количество',
    'product.description': 'Описание',
    'product.materials': 'Материалы',
    'product.care': 'Уход',
    'product.see.all': 'Все',
    'order.reference': 'Номер заказа',
    'order.status': 'Статус',
    'order.shipping': 'Доставка',
    'order.payment': 'Оплата',
    'order.arrival': 'Ожидаемая дата',
    'settings.panel': 'Панель управления',
    'checkout.title': 'Оформление',
    'checkout.contact': 'Контактная информация',
    'checkout.summary': 'Итог',
    'checkout.place': 'Заказать',
    'checkout.processing': 'Обработка...',
    'favorites.save': 'Сохраняйте любимые вещи',
    'favorites.discover': 'Посмотреть товары',
    'order.confirmed': 'ЗАКАЗ ПОДТВЕРЖДЕН',
    'order.confirmed.msg': 'Ваши вещи готовятся с заботой.',
    'order.tracking': 'Статус',
    'order.step.confirmed': 'Подтвержден',
    'order.step.processing': 'Обрабатывается',
    'order.step.shipped': 'Отправлен',
    'order.step.delivered': 'Доставлен',
    'order.ship.address': 'Адрес доставки',
    'order.pay.method': 'Способ оплаты',
    'product.rating': 'Рейтинг',
    'product.size.guide': 'Гид по размерам',
    'product.ecosystem': 'КОМПЛЕКТ',
    'product.complete': 'Дополните образ',
    'store.hero.title': 'ЗИМНЯЯ КОЛЛЕКЦИЯ',
    'store.highlight.tag': 'СЕРИЯ',
    'store.cat.all': 'Все',
    'store.cat.outerwear': 'Верхняя одежда',
    'store.cat.accessories': 'Аксессуары',
    'store.cat.tops': 'Верх',
    'store.cat.bottoms': 'Низ',
    'store.cat.shoes': 'Обувь',
    'product.size.text': 'Размер',
    'order.shipping.text': 'Доставка',
    'order.total.text': 'Итого',
    'order.complimentary': 'Бесплатно',
    'order.continue.shopping': 'ПРОДОЛЖИТЬ',
    'order.message.seller': 'НАПИСАТЬ ПРОДАВЦУ',
    'settings.version.suffix': '-ГЛЯЦИЙ',
    'admin.product.subcategory': 'Подкатегория',
    'admin.product.photos': 'Фото',
    'admin.form.basic_info': 'Основная информация',
    'admin.form.pricing': 'Цена и количество',
    'admin.form.details': 'Детали',
    'admin.form.upload': 'Загрузить',
    'admin.form.url': 'Ссылка',
    'admin.form.first_is_primary': 'первое фото — главное',
    'admin.form.add_photo': 'Добавить еще фото',
    'admin.no.products': 'Товаров еще нет',
    'products.empty.category': 'В этой категории еще нет товаров',
    'products.empty.hint': 'Попробуйте другую категорию или загляните позже',
    'admin.product.sizes_label': 'Размеры (нажмите, чтобы выбрать)',
    'admin.product.collections_label': 'Коллекции',
    'admin.form.custom_size': 'Свой размер',
    'admin.form.custom_collection': 'Новая коллекция',
    'admin.form.add': 'Добавить',
  },
};

type Lang = keyof typeof translations;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  plural: (n: number, one: string, few: string, many: string) => string;
}

const LangContext = createContext<LangContextValue | null>(null);

const LANG_STORAGE_KEY = 'cchrome_lang';

function loadLang(): Lang {
  try { const v = localStorage.getItem(LANG_STORAGE_KEY); if (v === 'UA' || v === 'RU') return v; } catch {}
  return 'UA';
}

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(loadLang);

  useEffect(() => {
    const tg = (window as any).Telegram?.WebApp;
    const chatId = tg?.initDataUnsafe?.user?.id;
    if (chatId) {
      fetch(`/api/user-lang?chatId=${chatId}`).then(r => r.json()).then(d => {
        if (d.lang && (d.lang === 'UA' || d.lang === 'RU')) {
          const stored = loadLang();
          if (!stored) {
            setLangState(d.lang);
            try { localStorage.setItem(LANG_STORAGE_KEY, d.lang); } catch {}
          }
        }
      }).catch(() => {});
    }
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try { localStorage.setItem(LANG_STORAGE_KEY, l); } catch {}
    const tg = (window as any).Telegram?.WebApp;
    const chatId = tg?.initDataUnsafe?.user?.id;
    if (chatId) {
      fetch('/api/user-lang', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chatId, lang: l }),
      }).catch(() => {});
    }
  }, []);

  const t = (key: string): string => {
    return (translations[lang] as Record<string, string>)[key] || key;
  };

  const plural = (n: number, one: string, few: string, many: string): string => {
    if (lang === 'UA') {
      if (n === 1) return one;
      if (n >= 2 && n <= 4) return few;
      return many;
    }
    return many;
  };

  return <LangContext.Provider value={{ lang, setLang, t, plural }}>{children}</LangContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
}